# Generated by Django 4.2.7 on 2024-01-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_klass_level_klass_user_student_klass'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subchapter',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.chapter'),
            preserve_default=False,
        ),
    ]
