# Generated by Django 4.2.7 on 2024-01-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_subchapter_file_url_alter_subchapter_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchapter',
            name='file_url',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
