# Generated by Django 4.2.7 on 2024-01-28 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_klass_level_klass_user_student_klass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='level',
            old_name='level',
            new_name='name',
        ),
    ]
