# Generated by Django 4.2.7 on 2024-01-27 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('answer_sheet_type', models.CharField(choices=[('SAME_TEST', 'All students have the same test'), ('UNIQUE_TEST', 'Each student has a unique test')], default='SAME_TEST', max_length=50)),
                ('no_of_questions', models.IntegerField()),
                ('simple_answer_list', models.CharField(default='', max_length=40)),
                ('rendered_html', models.TextField(default=None, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('ANALIZING', 'Analizing'), ('COMPLETED', 'Completed')], default='RUNNING', max_length=10)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('average_grades', models.FloatField(blank=True, null=True)),
                ('completion_rate', models.IntegerField(blank=True, default=0, null=True)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.klass')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('ans_a', models.CharField(max_length=100)),
                ('ans_b', models.CharField(max_length=100)),
                ('ans_c', models.CharField(max_length=100)),
                ('ans_d', models.CharField(max_length=100)),
                ('correct_ans', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('is_public', models.BooleanField()),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_questions', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_questions', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQs.test')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectAnswerList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_list', models.CharField(default='', max_length=40)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MCQs.test')),
            ],
        ),
    ]
