# Generated by Django 4.2.7 on 2024-02-25 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_chapter_name_alter_subchapter_name'),
        ('MCQs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapter'),
        ),
    ]
