# Generated by Django 4.2.7 on 2024-10-24 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MCQs', '0002_question_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MCQs.test'),
        ),
    ]
