# Generated by Django 4.2.7 on 2024-01-27 10:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('verified_email', models.BooleanField(default=False)),
                ('email_auth_token', models.CharField(blank=True, max_length=12)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_paid_member', models.BooleanField(default=False)),
                ('subscriber_id', models.CharField(blank=True, max_length=50, null=True)),
                ('subscription_status', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'useraccounts',
            },
        ),
    ]
