# Generated by Django 4.2.7 on 2024-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.FloatField(default=10)),
                ('yearly_price', models.FloatField(default=100)),
            ],
        ),
    ]
