# Generated by Django 4.2.7 on 2024-01-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_chapter_level_chapter_subject_subchapter_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subchapter',
            name='file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='subchapter_files/'),
        ),
    ]
