# Generated by Django 4.2.7 on 2024-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_chapter_name_alter_subchapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='subchapter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
