# Generated by Django 4.2.7 on 2024-10-24 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_chapter_name_alter_subchapter_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubChapter',
        ),
    ]
